import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import YAML from "yaml";
import { z } from "zod";
import {
  GRANULARITY_LADDER,
  OD_METRIC_LADDER,
  RESIDENT_COUNT_LADDER,
  RESIDENT_PLACEMENT_FORM_OPTIONS,
  WORKPLACE_COUNT_LADDER,
  WORKPLACE_PLACEMENT_FORM_OPTIONS,
} from "@subway-builder-modded/registry-schemas";
import {
  DEFAULT_MAP_DATA_SOURCE,
  SPECIAL_DEMAND_TAGS,
} from "../lib/map-constants.js";

const REPO_ROOT = resolve(import.meta.dirname, "..", "..");
const TEMPLATE_DIR = resolve(REPO_ROOT, ".github", "ISSUE_TEMPLATE");
const PUBLISH_TEMPLATE_PATH = resolve(TEMPLATE_DIR, "publish-map.yml");
const UPDATE_TEMPLATE_PATH = resolve(TEMPLATE_DIR, "update-map.yml");
const DATA_QUALITY_TEMPLATE_PATH = resolve(TEMPLATE_DIR, "data-quality.yml");
const GENERATED_HEADER =
  "# AUTO-GENERATED by scripts/intake/generate-map-templates.ts. Do not edit directly.";

const YAML_OPTIONS = {
  lineWidth: 92,
  indent: 2,
  defaultStringType: "QUOTE_DOUBLE",
  blockQuote: true,
  // GitHub's issue-form parser rejects YAML anchors/aliases, which the
  // emitter otherwise produces when dropdowns share an options array
  // (the whole template then falls back to the blank issue editor).
  aliasDuplicateObjects: false,
} as const;

const OptionItemSchema = z.union([
  z.string(),
  z.object({ label: z.string().min(1), required: z.boolean().optional() }).passthrough(),
]);

const MarkdownBodyItemSchema = z
  .object({
    type: z.literal("markdown"),
    attributes: z.object({ value: z.string().min(1) }).passthrough(),
  })
  .passthrough();

const NonMarkdownBodyItemSchema = z
  .object({
    type: z.enum(["input", "textarea", "checkboxes", "dropdown"]),
    id: z.string().min(1),
    attributes: z
      .object({
        label: z.string().min(1),
        description: z.string().min(1).optional(),
        placeholder: z.string().optional(),
        render: z.string().optional(),
        value: z.string().optional(),
        options: z.array(OptionItemSchema).optional(),
      })
      .passthrough(),
    validations: z.object({ required: z.boolean().optional() }).passthrough().optional(),
  })
  .passthrough();

const IssueFormSchema = z.object({
  name: z.string().min(1),
  description: z.string().min(1),
  title: z.string().min(1),
  labels: z.array(z.string().min(1)).min(1),
  body: z.array(z.union([MarkdownBodyItemSchema, NonMarkdownBodyItemSchema])).min(1),
});

type TemplateValue = Record<string, unknown>;
type TemplateField = {
  type: string;
  id: string;
  attributes: Record<string, unknown>;
  validations?: { required: boolean };
};
type FieldOptions = {
  placeholder?: string;
  value?: string;
  render?: string;
  required?: boolean;
};
type CheckboxOption = string | { label: string; required?: boolean };
type TemplateMode = "publish" | "update";
type TemplateDoc = {
  name: string;
  description: string;
  title: string;
  labels: string[];
  body: TemplateValue[];
};

function markdown(value: string): TemplateValue {
  return {
    type: "markdown",
    attributes: { value },
  };
}

function spacer(): TemplateValue {
  return markdown("<br>");
}

function input(
  id: string,
  label: string,
  description: string,
  opts: FieldOptions = {},
): TemplateValue {
  const item: TemplateField = {
    type: "input",
    id,
    attributes: { label, description },
  };
  if (opts.placeholder !== undefined)
    item.attributes.placeholder = opts.placeholder;
  if (opts.value !== undefined) item.attributes.value = opts.value;
  if (opts.required !== undefined)
    item.validations = { required: opts.required };
  return item;
}

function textarea(
  id: string,
  label: string,
  description: string,
  opts: FieldOptions = {},
): TemplateValue {
  const item: TemplateField = {
    type: "textarea",
    id,
    attributes: { label, description },
  };
  if (opts.render !== undefined) item.attributes.render = opts.render;
  if (opts.placeholder !== undefined)
    item.attributes.placeholder = opts.placeholder;
  if (opts.required !== undefined)
    item.validations = { required: opts.required };
  return item;
}

function checkboxes(
  id: string,
  label: string,
  description: string,
  options: readonly CheckboxOption[],
): TemplateValue {
  return {
    type: "checkboxes",
    id,
    attributes: {
      label,
      description,
      options: options.map((entry) =>
        typeof entry === "string" ? { label: entry } : entry,
      ),
    },
  };
}

function dropdown(
  id: string,
  label: string,
  description: string,
  options: readonly string[],
  required: boolean,
): TemplateValue {
  return {
    type: "dropdown",
    id,
    attributes: {
      label,
      description,
      options,
    },
    validations: {
      required,
    },
  };
}

function mapIdField(description: string): TemplateValue {
  return input("map-id", "Map ID", description, {
    required: true,
  });
}

function cloneTemplateDoc<T>(doc: T): T {
  return JSON.parse(JSON.stringify(doc)) as T;
}

function withTemplatePolicy(baseDoc: TemplateDoc, mode: TemplateMode): TemplateDoc {
  const doc = cloneTemplateDoc(baseDoc);

  for (const item of doc.body) {
    if (!item || typeof item !== "object") continue;
    const field = item as {
      type?: unknown;
      id?: unknown;
      attributes?: Record<string, unknown>;
      validations?: Record<string, unknown>;
    };
    const type = typeof field.type === "string" ? field.type : undefined;
    const id = typeof field.id === "string" ? field.id : undefined;

    // For dropdown fields, ensure there is a blank option at the top to allow users to leave it unchanged (for update) or to force them to make an active choice (for publish)
    if (type === "dropdown") {
      const attributes = field.attributes;
      if (attributes && Array.isArray(attributes.options) && attributes.options[0] !== "") {
        attributes.options = ["", ...attributes.options];
      }
    }

    // For update template, remove placeholder and default value hints since they may no longer be accurate and could mislead users into thinking they need to fill in every field
    if (mode === "update" && type !== "markdown" && id !== "map-id" && field.attributes) {
      delete field.attributes.placeholder;
      delete field.attributes.value;
    }

    // For update template, make all non-markdown fields optional since users only need to fill in the fields they want to change. The only required field is the map-id to identify which map to update.
    if (mode === "update" && type !== "markdown" && id !== "map-id") {
      const validations = field.validations;
      if (validations && typeof validations === "object" && "required" in validations) {
        validations.required = false;
      }
    }

    // Without this guard, selecting no special demand tags on update form would wipe all existing special demand tags since it is a zero-tolerant multiple choice checkbox
    if (mode === "update" && id === "special_demand" && field.attributes) {
      field.attributes.description =
        "Select tags only if you want to replace current special demand tags. Leave all unchecked to keep current tags.";
    }

    if (mode === "update" && id === "collaborators" && field.attributes) {
      field.attributes.description =
        "Leave blank to keep current collaborators. Enter `None` to clear. Otherwise, enter comma-separated GitHub user IDs to replace current collaborators.";
    }

    if (mode === "update" && id === "included-cities" && field.attributes) {
      field.attributes.description =
        "Leave blank to keep current additional cities. Enter `None` to clear. Otherwise, enter a comma-separated list to replace (e.g. `Gdynia, Sopot`).";
    }

    // The publish attestation describes the required data-quality step, which
    // only applies to NEW submissions; metadata updates never re-gate on it.
    if (
      mode === "update" &&
      type === "markdown" &&
      field.attributes &&
      typeof field.attributes.value === "string" &&
      field.attributes.value.startsWith("## Data Attestation")
    ) {
      field.attributes.value =
        "## Data Attestation\n\nProvide details about your map's data source. Be honest and transparent in your descriptions and please include the methodology you used to generate the map's data. See the [Data Quality](https://subwaybuildermodded.com/registry/docs/data-quality) guide for more information.\n\nUpdating metadata does not change your map's data-quality tier. If the underlying data changed, submit new answers via the [data-quality questions](https://subwaybuildermodded.com/registry/docs/data-quality/questions) form.";
    }
  }

  return doc;
}

const SHARED_FIELDS_AFTER_MAP_ID = [
  // ===== Data Validation ===== //
  input(
    "name",
    "City Name",
    "The human-readable city name shown in Railyard. This is the title of the map that people will see when downloading it.",
    { placeholder: "Raleigh", required: true },
  ),
  input(
    "included-cities",
    "Additional Cities",
    "Optional. Comma-separated list of major cities whose territory this map covers but whose names are not in the map name. Used to improve search discoverability — e.g. enter `Gdynia, Sopot` for a Gdańsk map, or `Bytom, Gliwice, Zabrze` for a Katowice map. Leave blank if the map name already reflects the coverage.",
    { placeholder: "Gdynia, Sopot", required: false },
  ),
  input(
    "city-code",
    "City Code",
    "2-4 letter IATA/ICAO-style city code used by the game internally. Must be uppercase letters/numbers. Must not clash with vanilla city codes or other registered maps. Check existing maps before choosing a code.",
    { placeholder: "RDU", required: true },
  ),
  input(
    "country",
    "Country Code",
    "ISO 3166-1 alpha-2 country code - two uppercase letters (e.g. US, GB, CA, DE, JP). Used to group maps by country in Railyard, and your map's location/region tag (e.g. `DE` → `central-europe`) is derived from it automatically. It is REQUIRED that you use ISO codes according to this list: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes.",
    { placeholder: "US", required: true },
  ),
  textarea(
    "description",
    "Description",
    "A short description of what your map offers. This is shown in the map browser. Mention data quality, notable features, or coverage area. To properly format your description, you can use the [Subway Builder Modded markdown playground](https://subwaybuildermodded.com/tools/md-playground).",
    {
      placeholder:
        "Custom map of the Raleigh-Durham metropolitan area with good demand data quality.",
      required: true,
    },
  ),
  spacer(),
  // ===== Data Validation ===== //
  markdown(
    "## Data Attestation\n\nProvide details about your map's data source. Be honest and transparent in your descriptions and please include the methodology you used to generate the map's data. See the [Data Quality](https://subwaybuildermodded.com/registry/docs/data-quality) guide for more information.\n\nAfter your submission is validated, you will be invited to answer the [data-quality questions](https://subwaybuildermodded.com/registry/docs/data-quality/questions) — a **required step**: your map cannot merge until a maintainer confirms your answers, and new submissions are subject to the [quality floor](https://subwaybuildermodded.com/registry/docs/data-quality/quality-floor) for countries with existing maps.",
  ),
  input(
    "data_source",
    "Data Source",
    "Enter the data source used to generate the demand data for your map. The source name should use common abbreviations like LODES/INSEE/ONS etc.",
    { placeholder: "LODES, etc.", value: DEFAULT_MAP_DATA_SOURCE, required: false },
  ),
  input(
    "methodology",
    "Methodology",
    "Description of how demand data was generated for your map. Please include any details about overcoming data source limitations or any augmentations done with real-world data.",
    { placeholder: "Transcribed raw OSM data", required: true },
  ),
  spacer(),
  // ===== Map Tagging / Images  ===== //
  markdown(
    "## Tagging & Image Preview\n\nRailyard allows users to search for maps based on tags and presents a preview image for discovery. Please check whichever tags best represent your map. Your map's location/region tag is derived automatically from the Country Code above.",
  ),
  markdown(
    "### Special Demand Tag Guide\n\nUse these tags only when the map models a meaningful amount of demand related to the feature.\n\n- `airports`: passenger (non-worker) demand from major airports\n- `entertainment`: leisure/tourist demand at stadiums/venues/nightlife\n- `ferries`: passenger (non-worker) demand from ferry terminals\n- `hospitals`: visitation demand for major medical centers\n- `parks`: leisure/tourist demand from large local or national parks\n- `schools`: demand from primary/secondary school students\n- `universities`: demand from university school students",
  ),
  checkboxes(
    "special_demand",
    "Special Demand",
    "Select all tags that apply to your map. These help users find your map in the browser.",
    SPECIAL_DEMAND_TAGS,
  ),
  textarea(
    "gallery",
    "Gallery Images",
    "Drag and drop screenshots here, or paste image URLs (one per line). These will be displayed in the map browser. At least one image is required.",
    { required: true },
  ),
  spacer(),
  // ===== Source Code Validation ===== //
  markdown(
    "## Source Code Information\n\nProvide information on where your map is hosted so that Railyard will be able to check your repository for updates and allow users to install the map on demand.",
  ),
  input(
    "source",
    "Source URL",
    "URL to your map's source code repository or download page.",
    { placeholder: "https://github.com/username/sb-raleigh", required: true },
  ),
  dropdown(
    "update-type",
    "Update Type",
    "The method used by Railyard to fetch updates for your map. Most maps should use GitHub Releases. Use Custom URL only if you host your own update.json file.",
    ["GitHub Releases", "Custom URL"],
    true,
  ),
  input(
    "github-repo",
    "GitHub Repository",
    "Required ONLY if you selected GitHub Releases. The `owner/repo` path (e.g. `username/sb-raleigh`). The repo must exist, have at least one release, and the latest release must contain a .zip asset. Leave blank if using Custom URL.",
    { placeholder: "username/sb-raleigh" },
  ),
  input(
    "custom-update-url",
    "Custom Update URL",
    "Required ONLY if you selected Custom URL. The full URL to your self-hosted update.json file. The file must follow the Railyard update.json schema. Leave blank if using GitHub Releases.",
    { placeholder: "https://example.com/sb-raleigh/update.json" },
  ),
  spacer(),
  // ===== Collaborators ===== //
  markdown(
    "## Collaborators",
  ),
  input(
    "collaborators",
    "Collaborators",
    "Optional comma-separated collaborator GitHub user IDs. Each ID must belong to an existing GitHub account.",
    { placeholder: "123456789, 987654321", required: false },
  ),
  spacer(),
  // ===== Authorization ===== //
  markdown(
    "## Authorization",
  ),
  {
    type: "checkboxes",
    id: "terms",
    attributes: {
      label: "Terms",
      options: [
        {
          label:
            "I attest that I am the author or this map or have been granted permission by the author to publish this map to Railyard.",
          required: true,
        },
        {
          label:
            "I attest that I have reviewed the Subway Builder Modded platform [Terms of Service](https://subwaybuildermodded.com/terms-of-service).",
          required: true,
        },
      ],
    },
  },
];

const publishTemplateBaseDoc: TemplateDoc = {
  name: "Publish New Map",
  description: "Submit a new custom map to The Railyard registry.",
  title: "[Publish Map]: ",
  labels: ["publish-map"],
  body: [
    markdown(
      "# Publish a New Map\n\nFill out the form below to submit your custom map to The Railyard. A pull request will be automatically created for review.\n\nIf validation fails, you can edit this issue and comment **revalidate** to retry.",
    ),
    spacer(),
    markdown(
      "## Identifiers\n\nProvide details about the city/metropolitan area your map models. These data will be used to import your map into the game and to give Railyard users context abour your map",
    ),
    mapIdField(
      "A unique identifier for your map in kebab-case. This is the permanent directory name in the registry and cannot be changed later. Must be unique across all maps - if another map of the same city already exists, use a distinct ID (e.g. `london-detailed`, `london-mini`). Only lowercase letters, numbers, and hyphens allowed.",
    ),
    ...SHARED_FIELDS_AFTER_MAP_ID,
  ],
};

const updateTemplateBaseDoc: TemplateDoc = {
  name: "Update Existing Map Metadata",
  description: "Update metadata for a map you own in The Railyard registry.",
  title: "[Update Map]: ",
  labels: ["update-map"],
  body: [
    markdown(
      "# Update Map Metadata\n\nOnly fill in the fields you want to change - leave everything else blank.\nYour GitHub account must match the original publisher of this map.\n\nIf validation fails, you can edit this issue and comment **revalidate** to retry.",
    ),
    spacer(),
    markdown(
      "## Identifiers\n\nProvide details about the city/metropolitan area your map models. These data will be used to import your map into the game and to give Railyard users context abour your map",
    ),
    mapIdField(
      "The ID of the map you want to update. Must already exist in the registry.",
    ),
    ...SHARED_FIELDS_AFTER_MAP_ID,
  ],
};

const publishTemplateDoc = withTemplatePolicy(publishTemplateBaseDoc, "publish");
const updateTemplateDoc = withTemplatePolicy(updateTemplateBaseDoc, "update");

// ===== Data-quality questions form (phase two of a submission) ===== //
// All option lists derive from the registry schemas ladders module — the
// single source of truth — so form wording and validator parsing cannot drift.

function ladderFormLabels(
  ladder: readonly { formLabel: string | null }[],
): string[] {
  return ladder
    .map((rung) => rung.formLabel)
    .filter((label): label is string => label !== null);
}

const GRANULARITY_FORM_LABELS = ladderFormLabels(GRANULARITY_LADDER);

const dataQualityTemplateBaseDoc: TemplateDoc = {
  name: "Map Data Quality",
  description:
    "Answer the data-quality questions for a map you own so it can receive its data-quality tier.",
  title: "[Data Quality]: ",
  labels: ["data-quality"],
  body: [
    markdown(
      "# Map Data Quality\n\nThese questions classify the census / official data behind your map so it can receive a data-quality tier. Every question is optional — **leaving a question blank is always safe** — but unanswered questions may keep the map at `unknown-quality` until a reviewer works through them with you.\n\nPlease read the [Submission Questions guide](https://subwaybuildermodded.com/registry/docs/data-quality/questions) — it explains each question in plain language, including the golden rule: **answer with where the numbers are published, not where you placed them**.\n\nYour answers produce a provisional score in a pull request; a reviewer confirms it before the tier appears.\n\nIf validation fails, you can edit this issue and comment **revalidate** to retry.",
    ),
    spacer(),
    mapIdField(
      "The ID of the map these answers describe. Must already exist in the registry — or have an open publish submission — and be published by your GitHub account.",
    ),
    dropdown(
      "same-methodology",
      "Same methodology as your other maps in this country?",
      "Answer Yes if this map's demand data was generated with the same methodology/pipeline as your existing scored maps in this country — its answers will be inherited from them and you may leave the remaining questions blank. See the sample list below (or the comment that linked you here) for the maps this refers to.",
      [
        "Yes — same methodology as my other maps in this country",
        "No — new or different methodology",
      ],
      false,
    ),
    input(
      "same-methodology-sample",
      "Same-Methodology Sample (reference)",
      "Auto-filled when you arrive via a prefilled link — the maps a Yes answer inherits from. Display-only: the registry re-derives the authoritative list, so it is safe to leave blank.",
      {
        placeholder:
          "Leave blank — auto-filled by the invite link; the registry derives the real list either way.",
        required: false,
      },
    ),
    spacer(),
    markdown(
      "## Workplace data\n\nWhere people **work** is the destination side of every commute, and it counts the most toward the map's final score.",
    ),
    dropdown(
      "dq-workplace-source",
      "Where do your job numbers come from?",
      "The key distinction: does your source know where people actually work, or only where their employer is registered? If unsure: check whether the source's documentation says \"place of work\" (or equivalent phrasing) — if present, select the first option; if you can't tell, name the source in Methodology and the reviewer will classify it.",
      ladderFormLabels(WORKPLACE_COUNT_LADDER),
      false,
    ),
    dropdown(
      "dq-workplace-detail",
      "What is the smallest area your job numbers are reported for?",
      "Follow the guide's Rule 1: answer with the source table's areas, not the map's demand points. If unsure: open the source table and look at what one row covers; when two grains are plausible, pick the coarser one and mention both in Methodology. See the guide's data-suppression note.",
      GRANULARITY_FORM_LABELS,
      false,
    ),
    dropdown(
      "dq-workplace-placement",
      "When a job number covers an area bigger than one building, how did you place the jobs within it?",
      "This is where the spreading from Rule 1's example gets its credit. If unsure: describe the placement approach in Methodology; this is the question where a brief description helps reviewers most.",
      WORKPLACE_PLACEMENT_FORM_OPTIONS.map((option) => option.formLabel),
      false,
    ),
    spacer(),
    markdown(
      "## Residence data\n\nWhere people **live** is the origin side of the commute. The submission asks the same three questions as for the workplace side.",
    ),
    dropdown(
      "dq-residence-source",
      "What do your population numbers count?",
      "Not all \"population\" is the same population. If unsure: look for the words \"employed\", \"economically active\", or an age breakdown in your source — a plain \"population\" table is almost always total population.",
      ladderFormLabels(RESIDENT_COUNT_LADDER),
      false,
    ),
    dropdown(
      "dq-residence-detail",
      "What is the smallest area your population numbers are reported for?",
      "As with the workplace question: follow the guide's two rules — answer with the source table's areas — and account for potential data suppression.",
      GRANULARITY_FORM_LABELS,
      false,
    ),
    dropdown(
      "dq-residence-placement",
      "When a population number covers an area bigger than one building, how did you place the people within it?",
      "The residence equivalent of the workplace placement; the main difference is that high-fidelity placement uses dwelling counts or residential floor area rather than workplace types. Answer this independently — many pipelines place jobs and people differently.",
      RESIDENT_PLACEMENT_FORM_OPTIONS.map((option) => option.formLabel),
      false,
    ),
    spacer(),
    markdown(
      "## Commute flows\n\nThe pairing of who commutes **from** where **to** where. This data is often hard to find, and its absence is acceptable; what is scored is whether real flow data (or real totals) constrain the estimates.",
    ),
    dropdown(
      "dq-od",
      "Does the census publish data about where people commute from and to?",
      "The idea behind the options: estimates that are forced to add up to real, measured totals count for more than estimates that were never checked against anything. If unsure: if you used any commuting or origin-destination table at all, describe it in Methodology.",
      ladderFormLabels(OD_METRIC_LADDER),
      false,
    ),
    dropdown(
      "dq-od-detail",
      "If you have commute-flow data, what is the smallest area it covers?",
      "Only answer this if the previous question selected one of the first three options — it asks for the areas the commute table's origins and destinations refer to (a table of town-to-town flows covers whole towns). Leave it blank if there is no flow data — the grain of estimated flows is not scored.",
      GRANULARITY_FORM_LABELS,
      false,
    ),
    spacer(),
    markdown(
      "## Methodology",
    ),
    textarea(
      "methodology",
      "Methodology",
      "The dropdown answers classify the data; use this space to describe the overall pipeline. A good methodology note includes: your sources with links; the pipeline in a few sentences; anything the dropdowns don't capture; and data vintages. Reviewers read this first — it is how ambiguous answers are resolved favorably rather than conservatively.",
      { required: true },
    ),
    textarea(
      "sources",
      "Data Source Links",
      "Links to the actual tables or datasets behind the answers, one per line.",
      { required: false },
    ),
  ],
};

function normalizeNewlines(content: string): string {
  return content.replace(/\r\n/g, "\n");
}

function buildTemplateFile(doc: TemplateValue): string {
  return `${GENERATED_HEADER}\n${YAML.stringify(doc, YAML_OPTIONS)}`;
}

function failValidation(label: string, error: z.ZodError): never {
  const details = error.issues
    .map((issue) => `${issue.path.join(".") || "/"} ${issue.message}`)
    .join("\n");
  throw new Error(
    `Schema validation failed for ${label}${details ? `:\n${details}` : "."}`,
  );
}

function validateTemplateDoc(label: string, doc: TemplateValue): void {
  const result = IssueFormSchema.safeParse(doc);
  if (!result.success) {
    failValidation(label, result.error);
  }
}

function parseTemplateFile(path: string): TemplateValue {
  const raw = normalizeNewlines(readFileSync(path, "utf-8"));
  const parsed = YAML.parse(raw) as unknown;
  if (!parsed || typeof parsed !== "object") {
    throw new Error(`Failed to parse YAML object from ${path}`);
  }
  return parsed as TemplateValue;
}

function getFieldId(item: unknown): string | undefined {
  if (!item || typeof item !== "object") return undefined;
  const candidate = item as { id?: unknown };
  return typeof candidate.id === "string" ? candidate.id : undefined;
}

function verifySharedTail() {
  const publishMapIdIndex = publishTemplateBaseDoc.body.findIndex(
    (item) => getFieldId(item) === "map-id",
  );
  const updateMapIdIndex = updateTemplateBaseDoc.body.findIndex(
    (item) => getFieldId(item) === "map-id",
  );

  if (publishMapIdIndex === -1 || updateMapIdIndex === -1) {
    throw new Error("Template bodies must include a `map-id` field.");
  }

  const publishTail = JSON.stringify(publishTemplateBaseDoc.body.slice(publishMapIdIndex + 1));
  const updateTail = JSON.stringify(updateTemplateBaseDoc.body.slice(updateMapIdIndex + 1));
  if (publishTail !== updateTail) {
    throw new Error("Template bodies after map-id must remain identical.");
  }
}

function stableStringify(value: unknown): string {
  return JSON.stringify(value);
}

function main(): void {
  verifySharedTail();
  validateTemplateDoc("publish-map (generated)", publishTemplateDoc);
  validateTemplateDoc("update-map (generated)", updateTemplateDoc);
  validateTemplateDoc("data-quality (generated)", dataQualityTemplateBaseDoc);

  const publishContent = buildTemplateFile(publishTemplateDoc);
  const updateContent = buildTemplateFile(updateTemplateDoc);
  const dataQualityContent = buildTemplateFile(dataQualityTemplateBaseDoc);
  const isCheckMode = process.argv.includes("--check");

  if (!isCheckMode) {
    writeFileSync(PUBLISH_TEMPLATE_PATH, publishContent);
    writeFileSync(UPDATE_TEMPLATE_PATH, updateContent);
    writeFileSync(DATA_QUALITY_TEMPLATE_PATH, dataQualityContent);
    console.log("Generated publish-map.yml, update-map.yml, and data-quality.yml");
    return;
  }

  const publishActual = parseTemplateFile(PUBLISH_TEMPLATE_PATH);
  const updateActual = parseTemplateFile(UPDATE_TEMPLATE_PATH);
  const dataQualityActual = parseTemplateFile(DATA_QUALITY_TEMPLATE_PATH);
  validateTemplateDoc("publish-map (checked)", publishActual);
  validateTemplateDoc("update-map (checked)", updateActual);
  validateTemplateDoc("data-quality (checked)", dataQualityActual);

  const publishMatches =
    stableStringify(publishActual) === stableStringify(publishTemplateDoc);
  const updateMatches =
    stableStringify(updateActual) === stableStringify(updateTemplateDoc);
  const dataQualityMatches =
    stableStringify(dataQualityActual) === stableStringify(dataQualityTemplateBaseDoc);

  if (!publishMatches || !updateMatches || !dataQualityMatches) {
    console.error("Map issue templates are out of date.");
    console.error("Run: pnpm --dir scripts run generate-map-templates");
    process.exit(1);
  }
  console.log("Map issue templates are in sync.");
}

main();
