blank_issues_enabled: false
contact_links:
  - name: Subway Builder Modded Discord
    url: https://discord.gg/syG9YHMyeG
    about: Get help or discuss custom content
  - name: Documentation
    url: https://subwaybuildermodded.com/https://subwaybuildermodded.com/railyard/docs/v0.2/developers/
    about: Read the submission documentation
