name: Announce New Asset
on:
  push:
    branches:
      - main
    paths:
      # Trigger when manifest files are updated in any subdirectory of mods or maps
      - 'mods/**/manifest.json'
      - 'maps/**/manifest.json'

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to compare with previous commit
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: scripts/pnpm-lock.yaml

      - name: Install script dependencies
        run: pnpm install --frozen-lockfile
        working-directory: scripts

      - name: Check if file was created
        id: check_file
        run: |
          if git diff --name-status HEAD^ HEAD | grep "A" | cut -f2 | grep "manifest.json"; then
            echo "file_created=true" >> $GITHUB_OUTPUT
            echo "file_name=$(git diff --name-status HEAD^ HEAD | grep "A" | cut -f2 | grep "manifest.json") >> $GITHUB_OUTPUT
          else
            echo "file_created=false" >> $GITHUB_OUTPUT
          fi
      - name: Release announcement
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_ANNOUNCEMENT_WEBHOOK_URL }}
        if: steps.check_file.outputs.file_created == 'true'
        run: pnpm --dir scripts run make-announcement "$(echo ${{ steps.check_file.outputs.file_name }})"
          